Support csv format from customer list
papercups-io/papercups pull request #325
Opened 2020-10-18 21:28 UTC by alisinabh

### Description

 - Add CSVHelpers module with a dump function.
 - Add view selection based on `format` parameter.
 - Add controller test for retrieving a csv customer list.
 - Change customer view to handle csv rendering.

### Issue

#324 

## Checklist

- [ ] Everything passes when running `mix test`
- [ ] Ran `mix format`
- [ ] No frontend compilation warnings

2020-10-19 02:22 UTC, reichert621 requested changes
looks great @alisinabh! 🎉  just a couple small things

2020-10-19 02:22 UTC, reichert621 commented on lib/chat_api_web/views/customer_view.ex
> +  @customer_csv_ordered_fields ~w(id name email created_atm updated_at)a ++
small typo: `created_atm` -> `created_at`

2020-10-19 02:22 UTC, reichert621 commented on lib/chat_api_web/views/customer_view.ex
> +                                 ~w(os ip metadata time_zone)a
let's just remove `metadata` for now (since it's a `map`/`json` field, and might break things)

2020-10-19 02:22 UTC, reichert621 commented on test/chat_api_web/controllers/customer_controller_test.exs
> +      assert csv =~ "\"#{customer.id}\","
nit - let's expand this a bit to verify that other fields are being properly included 👍

2020-10-19 12:32 UTC, fel-mazo commented
nicely done

2020-10-19 17:03 UTC, reichert621 reviewed
hey @alisinabh! sorry, one last comment 😅 just want to make sure we have a test file for the `CSVHelpers` module!

2020-10-19 17:03 UTC, reichert621 commented on lib/chat_api_web/views/csv_helpers.ex
> +defmodule ChatApiWeb.CSVHelpers do
could we add some tests for this module as well? (sorry I missed this in the first review!)

2020-10-20 20:57 UTC, merged

2020-10-20 20:57 UTC, reichert621 commented
merging for now, but if you could add more tests for the CSV helper module in a separate PR that would be great! :tada:

2020-10-21 00:06 UTC, alisinabh commented
Hi @reichert621 

Thank you for the merge. I am terribly sorry I wasn't available. I am a bit busy but will add tests for `CSVHelpers` ASAP.

:heart: